### PR TITLE
ci: sync release branch

### PR DESCRIPTION
**Pull request by PaulRBerg**
Adds a CI workflow for syncing the `v1` branch every time a new git tag that starts with `v1` is pushed to remote.

### CODE REVIEW

**Review by mds1 — APPROVED** [review]
Oh this is awesome, thanks!

**Comment by PaulRBerg** [comment]
Note: I have never used this workflow before.

I guess this means we'll test in prod.

**Comment by mds1** [comment]
Good to know, thanks. It seems simple enough though, I'll keep an eye out during the next release

**Comment by mds1** [comment]
Just put out v1.5.5, looks like it worked! 🎉
- https://github.com/foundry-rs/forge-std/tree/v1
- https://github.com/foundry-rs/forge-std/actions/runs/4844732554

**Comment by PaulRBerg** [comment]
Glad to hear - it's rare that things work the first time, even simple ones.

**Pull request merged**
