### PR TITLE
Add signP256 cheatcode

### PR DESCRIPTION
**Pull request by wilsoncusack**
Follow up to https://github.com/foundry-rs/foundry/pull/6797, adds function definition for signP256 to Vm.sol

### CODE REVIEW

**Comment by wilsoncusack** [comment]
@mds1 
image

**Comment by mds1** [comment]
@DaniPopes I'm looking at https://github.com/foundry-rs/foundry/pull/6785 and it aded a new group called `Base64`. Feels like overkill for that to have it's own group. What do you think about removing that group and moving the base64 cheats to the `Utilities` group?

**Comment by wilsoncusack** [comment]
Does it make sense to leave the byes64 issue to a separate PR?

**Comment by mds1** [comment]
Replaced by https://github.com/foundry-rs/forge-std/pull/497

**Pull request closed without merging**
