### PR TITLE
Add vm.unixTime to VmSafe interface

### PR DESCRIPTION
**Pull request by Tudmotu**
Following https://github.com/foundry-rs/foundry/pull/5952.
Adding `vm.unixTime()` cheatcode to `VmSafe` interface.
I tested this change manually on my machine.

### CODE REVIEW

**Comment by mds1** [comment]
Thanks! Sorry for the conflicts, but I just merged https://github.com/foundry-rs/forge-std/pull/464 which has two main changes:
1. It refactors the `Vm` file quite a bit to be more organized
2. It adds a test to verify we didn't *accidentally* change the Vm interfaces

Could you fix the conflicts on this branch as a result? We can put the new cheat in `VmSafe` under the "Filesystem" comment block. (I think we should rename that section to "OS and Filesystem", then move the two `ffi` cheats from the "External Interactions" into that section too, and delete "External Interactions". If you want to do that, that'd be awesome! No worries if not though)

Then you'll also need to update the failing test based on whatever the new interfaceId is

**Comment by Tudmotu** [comment]
Hi @mds1 thanks for the heads up.
I updated my branch with your asks. I was not sure what should I name the new "subsections".
I named them "Running executables" and "System information". Please let me know what you think:
image
 
 I can change these if you'd like me to name them something else.

**Review by mds1 — APPROVED** [review]
Thank you!

**Comment by Tudmotu** [comment]
TIL what `ffi` means haha
Thanks for merging @mds1 :pray:

**Pull request merged**
