### PR TITLE
fix: CapWords naming style

### PR DESCRIPTION
**Pull request by shawnharmsen**
issue: https://github.com/foundry-rs/forge-std/issues/13

Not sure if the issue is still relevant haha

Regarding test
- I saw that ci does forge test -vvv
https://github.com/foundry-rs/forge-std/blob/37a3fe48c3a4d8239cda93445f0b5e76b1507436/.github/workflows/tests.yml#L20-L21

Are there other things I should be doing for testing?

### CODE REVIEW

**Review by ZeroEkkusu — COMMENTED** [review]
Thanks!

This is a breaking change so let's see how we should approach it. Cc @mds1.

> Are there other things I should be doing for testing?

`forge test -vvv` was enough in this case. But when you change code or add new features in `Test`, you also want to check compatibility with older solc versions, as done in the CI.

### Edit

We should rename `stdStorage` (the library) to `StdStorage` as well.

Thoughts on renaming `StdStorage` (the struct) to `StdStore` then?

That way it would match with the name of the variable. We'd then use the library like so:

```solidity
using StdStorage for StdStore;

function f() public {
    stdstore.target(address(c)). //...
```

We can also rename `stdstore` to `stdStore`.

**Comment by mds1** [comment]
We should probably sync this with the next planned foundry breaking change. @gakonst @onbjerg is there anywhere that tracks a list of breaking changes planned for a future release? Wondering the best way logistically to keep these in sync

**Comment by gakonst** [comment]
This large naming change seems unnecessary for now..the `Console.sol` change I'm against because it means I'd need to do `Console.log("foo")` whereas `console.log` is nicer. 

I'd vote to close #13 as #wontfix given that this is a stylistic change on a testing lib which doesn't seem to be exposed to the user in many ways?

**Comment by ZeroEkkusu** [comment]
#13 is a relatively old issue (`console` wasn't even part of Forge Std).

As I said recently, I still like the idea of following the CapWords convention, but don't like breaking things.

Best to decide now, and if we're not going to do it, close as wontfix as Georios proposed.

**Comment by mds1** [comment]
Agree that `console` should stay lowercase (sorry, hadn't looked at the diff yet). 

IIUC the reason this is a breaking change is because users need to access e.g. `stdError.arithmeticError` and `using stdStorage for StdStorage`? It'd be nice if that was `StdError` and `StdStorage`, because that's the convention used pretty much everywhere else, but obviously this isn't a huge deal so I'm fine leaving as-is. Plus then we also have to rename the struct anyway to avoid a name conflict. So I think I've talked myself into agreeing we close this PR + #13 and leave as-is for now

**Comment by gakonst** [comment]
@shawnharmsen thanks for the contribution, I think we'll close this for now given the arguments brought up above. LMK if you think this is unreasonable and we can discuss ways we can incorporate in future releases while being sensitive of breakages!

**Pull request closed without merging**
