### PR TITLE
Fix long compile times when using `via-ir`

### PR DESCRIPTION
**Pull request by Vectorized**
For #207.

Tested on Solady. Compiles within 2 minutes instead of 30+ minutes.

### CODE REVIEW

**Comment by mds1** [comment]
Thanks! This is a great workaround, minimal UX hit 👌

I just want to see how #207 shakes out before merging this, it's possible there's a solc or svm-rs issue which would mean we can leave things as-is, which would be preferable IMO

**Comment by marktoda** [comment]
We've been suffering wildly long compile times as well, this commit fixes for us too :ok_hand: Seems like maybe a faster way forward than a compiler-level fix? ie might be worth it for dev ex to merge this now and revert if the underlying issue is later resolved in 0.8.18 or something, given forge releases much more often than solc

**Comment by ZeroEkkusu** [comment]
In order to restore `--via-ir` and not hurt the adoption of V1, we can do the following:

1. Remove the `stdChains` variable completely (no half-backed features); keep `assumeNoPrecompiles` (hardcode chain IDs)
3. Find a solution (#207)
4. Put `stdChains` back

Interested if others would find this to be a good solution.

Another idea: We can can change `stdChains` to be a mapping, e.g. `stdChains["mainnet"]`, if that helps with this issue (have not tested). It would also allow users to add custom chains to `stdChains`.

**Comment by mds1** [comment]
Per some discussion in the foundry telegram, let's
- refactor to mapping approach due to added flexibility (also nice that the keys to access chain data matches the expected keys in the config file)
- test to make sure that it doesn't have the slow compile time issue
- if not, merge. if it does, use the struct with the solution in this PR

**Comment by ZeroEkkusu** [comment]
Thanks for reporting the issue, @Vectorized! We are closing your PR, as we’ve implemented a solution with mappings in #217.

I hope you’ll like Forge-Std 1.1 better!

**Pull request closed without merging**
