### PR TITLE
feat: pure `console.log`s

### PR DESCRIPTION
**Pull request by 0xdapper**
h/t @0age https://twitter.com/z0age/status/1654922202930888704

Thought about creating a different console3.sol but there is no downside to just making everything pure.

### CODE REVIEW

**Comment by mds1** [comment]
Awesome, thank you! Was hoping someone would PR this, really clever workaround

I'll take a closer look tomorrow or monday before merging, but can we revert the changes to `console.sol`? That one is left untouched to ensure compatibility with hardhat, whereas `console2.sol` fixes the original selector issues of `console.sol` + we can modify/extend it for forge as needed

**Comment by 0xdapper** [comment]
I don't think this should break the compatibility with hardhat

**Comment by mds1** [comment]
I also don't think it should break the compatibility with hardhat, but I haven't tested to confirm, so would prefer to leave it unless there's a reason to change it. Not sure who uses `console.sol` or what assumptions hardhat makes about it. I guess one downside of changing it is that now anyone using `console.sol` in hardhat projects with minimal forge usage now get compiler warnings about function visibility 🤷

Aside from that this PR lgtm

**Review by mds1 — APPROVED** [review]
looks great, thank you 🫡

**Review by mds1 — APPROVED** [review]
looks great, thank you 🫡

**Pull request merged**
